caloriesgame/models.py
#models.py
from caloriesgame import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
	return User.query.get(user_id)

# friends = db.Table('friends',
# 	db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
# 	db.Column('friend_id', db.Integer, db.ForeignKey('user.id'))
# )

class User(db.Model, UserMixin):
	
	__tablename__ = 'users'

	id = db.Column(db.Integer, primary_key=True)
	avatar = db.Column(db.String(128),nullable=False,default='./default_avatar.png')
	email = db.Column(db.String(128), unique=True, index=True)
	username = db.Column(db.String(128), index=True)
	password_hash = db.Column(db.String(128))
	age = db.Column(db.Integer, default='20')
	current_weight = db.Column(db.Float, default='60')

	workouts = db.relationship('WorkoutSession', backref='owner', lazy='dynamic')
	
	#relationships:
	#a list of integer for friend ids
	#friends

	#each user has many pks
	#pks = db.relationship('PK',backref='contestant',lazy=True)

	#each user has many interests
	#interests = db.relationship('Exercise')

	# friends = db.relationship('User', #defining the relationship, User is left side entity
 #        secondary = friends, 
 #        primaryjoin = (friends.c.user_id == id), 
 #        secondaryjoin = (friends.c.friend_id == id),
 #        lazy = 'dynamic'
 #    ) 


	def __init__(self,email,username,password):
		self.email = email
		self.username = username
		self.password_hash = generate_password_hash(password)

	def check_password(self, password):
		return check_password_hash(self.password_hash,password)

	def __repr__(self):
		return f"Username: {self.username}"




class WorkoutSession(db.Model):
	id = db.Column(db.Integer,primary_key=True)
	users = db.relationship(User)
	user_id = db.Column(db.Integer, db.ForeignKey('users.id'),nullable=False)
	date = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
	timeLasted = db.Column(db.Integer,nullable=False)

	def __init__(self,user_id,timeLasted):
		self.user_id = user_id
		self.timeLasted = timeLasted
	
	def __repr__(self):
		return f"workout id: {self.id}"

caloriesgame/groups/forms.py
#forms.py

caloriesgame/users/forms.py
#forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed

from flask_login import current_user
from caloriesgame.models import User

class Login(FlaskForm):
	email = StringField('Email', validators = [DataRequired(),Email()])
	password = PasswordField('Password', validators = [DataRequired()])
	submit = SubmitField('Sign In')

class Registration(FlaskForm):
	email = StringField('Email', validators=[DataRequired(),Email()])
	username = StringField('UserName', validators=[DataRequired()])
	password = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm', message='Passwords Dont Match!')])
	pass_confirm = PasswordField('Confirm password', validators=[DataRequired()])
	submit = SubmitField('Sign up')

	def validate_email(self,email):
		if User.query.filter_by(email=self.email.data).first():
			raise ValidationError('This email address already exists!')


class UpdateUserInfo(FlaskForm):
	username = StringField('UserName', validators=[DataRequired()])
	avatar = FileField('Edit Avatar',validators=[FileAllowed(['png','jpg'])])
	submit = SubmitField('Update')

caloriesgame/__init__.py
# caloriesgame/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


app = Flask(__name__)
###################
#### DATABASE #####
###################
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

app.config['SECRET_KEY'] = 'bicileta'

db = SQLAlchemy(app)
Migrate(app,db)

login_manager = LoginManager()

login_manager.init_app(app)
login_manager.login_view = 'users.login'


###################
from caloriesgame.main.views import main
from caloriesgame.error_pages.handlers import error_pages
from caloriesgame.users.views import users

app.register_blueprint(main)
app.register_blueprint(error_pages)
app.register_blueprint(users)

caloriesgame/exercises/__init__.py
#__init__.py

caloriesgame/exercises/views.py
views.py

caloriesgame/groups/__init__.py
#__init__.py

caloriesgame/groups/views.py
views.py

caloriesgame/main/views.py
# main/views.py

from flask import render_template, request, Blueprint

main = Blueprint('main', __name__)

@main.route('/')
def index():
	return render_template('index.html')

@main.route('/info')
def info():
	return render_template('info.html')

caloriesgame/pks/__init__.py
#__init__.py

caloriesgame/pks/views.py
#views.py

caloriesgame/users/__init__.py
#__init__.py

caloriesgame/users/views.py
#users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from caloriesgame import db
from caloriesgame.models import User, WorkoutSession
from caloriesgame.users.forms import Registration, Login, UpdateUserInfo
from caloriesgame.users.picture_handler import add_profile_pic
from werkzeug.security import generate_password_hash,check_password_hash

users = Blueprint('users', __name__)


#register
@users.route('/register', methods=['GET','POST'])
def register():
    form = Registration()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Registration Successful!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


#login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        # Grabbing the user from the User Models table
        user = User.query.filter_by(email=form.email.data).first()

        # Check that the user was supplied and the password is right
        # The verify_password method comes from the User object
        # https://stackoverflow.com/questions/2209755/python-operation-vs-is-not

        if user.check_password(form.password.data) and user is not None:
            #Log in the user

            login_user(user)
            flash('Log in Success!')


            #either go to the targeted page or back to the home page

            #If a user was trying to visit a page that requires a login
            #flask saves that URL as 'next'
            next = request.args.get('next')

            #check if that next exists, otherwise we'll go to
            #the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('main.index')

            return redirect(next)
    return render_template('login.html', form=form)


#logout
@users.route('/logout')
def logout():
	#built-in function
	logout_user()

	#direct back to home page
	return redirect(url_for("main.index"))

#profile page
@users.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserInfo()

    if form.validate_on_submit():
        print(form)
        if form.avatar.data:
            username = current_user.username

            #using picture_handler.py functions
            pic = add_profile_pic(form.avatar.data,username)

            current_user.avatar = pic
        current_user.username = form.username.data
        db.session.commit()
        flash('Profile Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username

    profile_image = url_for('static', filename='profile_pics/' + current_user.avatar)
    return render_template('account.html', avatar=profile_image, form=form)

#page for each user
@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    workout_sessions = WorkoutSession.query.filter_by(owner=user).order_by(WorkoutSession.date.desc()).paginate(page=page, per_page=10)
    return render_template('user_workouts.html', workout_sessions=workout_sessions, user=user)
#list of pks

caloriesgame/templates/account.html
{% extends "base.html" %}
{% block content %}

  <div class="jumbotron">
    <div align='center'>
      <h1 >Profile Page for {{current_user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.avatar) }}">
    </div>
  </div>
  <div class="container">
    <form  method="POST" action = "" enctype="multipart/form-data">
      {# for security #}
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username.label(class="form-group") }}
        {{form.username(class='form-control')  }}
      </div>
      <div class="form-group">
        {{ form.avatar.label(class="form-group") }}
        {{ form.avatar(class="form-control-file") }}
      </div>
      <div class="form-group">
          {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>

  </div>

{% endblock content %}

caloriesgame/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
	   <ul class='nav'>
      <li class='nav-link'>
        <a href="{{ url_for('main.index') }}">Home</a>
      </li>
      <li class='nav-link'>
        <a href="{{ url_for('main.info') }}">About</a>
      </li>
        {% if current_user.is_authenticated %}
          <li class='nav-link'>
            <a href="{{ url_for('users.logout') }}">Log Out</a>
          </li>
          <li class='nav-link'>
            <a href="{{ url_for('users.account') }}">Account</a>
          </li>
          <li class='nav-link'>
            <a href="#">Add a Workout Session</a>
          </li>
        {% else %}
          <li class='nav-link'>
            <a href="{{ url_for('users.login') }}">Log In</a>
          </li>
          <li class='nav-link'>
            <a href="{{ url_for('users.register') }}">Register</a>
          </li>
        {% endif %}
    </ul>

<div class="container">
  {% block content %}

  {% endblock %}
</div>

</body>
</html>

caloriesgame/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Calories Game !</h1>
  </div>
{% endblock %}

caloriesgame/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Info about our web app</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>

    <div class="jumbotron">
    <h1>Info about our team members</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
{% endblock %}

caloriesgame/templates/login.html
{% extends "base.html" %}
{% block content %}
	<form method="POST">
	    {# This hidden_tag is a CSRF security feature. #}
	    {{ form.hidden_tag() }}
	    {{ form.email.label }} {{ form.email() }}<br>
	    {{ form.password.label }} {{ form.password() }}<br>
	    {{ form.submit() }}
	</form>
{% endblock %}

caloriesgame/templates/register.html
{% extends "base.html" %}
{% block content %}
	<form method="POST">
	    {# This hidden_tag is a CSRF security feature. #}
	    {{ form.hidden_tag() }}
	     <div class="form-group">
	    	{{ form.email.label }} {{ form.email(class="form-group") }}<br>
		</div>
		<div class="form-group">
	    	{{ form.username.label }} {{ form.username(class="form-group") }}<br>
	    </div>
	    <div class="form-group">
	    	{{ form.password.label }} {{ form.password(class="form-group") }}<br>
	    </div>
	    <div class="form-group">
	    	{{ form.pass_confirm.label }} {{ form.pass_confirm(class="form-group") }}<br>
	    </div>
	    {{ form.submit() }}
	</form>
{% endblock %}

caloriesgame/templates/user_workouts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for w in workout_sessions.items %}

          <!-- <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=w.id) }}">{{ w.title }}</a></h2> -->
          workout done by: <a href="{{ url_for('users.workoutsessions', username=w.owner.username) }}">{{ w.owner.username }}</a>
          <p class="text-muted">uploaded on: {{ w.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>The workout lasted for {{w.timeLasted}} minuets.</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in workout_sessions.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if workout_sessions.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.workout_sessions', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}